# Generated by Django 4.2.4 on 2023-08-05 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0003_movie_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='raring',
            new_name='rating',
        ),
    ]
